name: flutter_osouji
description: Fast parallel Flutter project cleaner that sweeps build artifacts with smart detection and real-time progress tracking.
version: 0.2.0
homepage: https://github.com/soraef/flutter_sweep
repository: https://github.com/soraef/flutter_sweep
issue_tracker: https://github.com/soraef/flutter_sweep/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.5.0
  mason_logger: ^0.2.11
  pool: ^1.5.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  flutter_osouji:
